### ISSUE TITLE
celery 4.1 worker tasks aren't being traced with ddtrace-py 0.26.0

### ISSUE THREAD

**Issue by eedwards-sk** [DataDog/dd-trace-py#1011]
This is a follow up to #451

It appears there is a regression, and autodiscovered tasks are no longer being traced again.

**Comment by brettlangdon** [comment]
@eedwards-sk thanks for reporting. we'll work on triaging and reproducing on our end.

are you still using `@shared_task` to register your tasks?

**Comment by eedwards-sk** [comment]
@brettlangdon hey brett, that's correct, we're using `@shared_task` and `app.autodiscover_tasks()`

**Comment by eedwards-sk** [comment]
We're still without tracing for celery tasks, and now facing diagnostic issues that we cannot surface due to lack of traces.

**Comment by Kyle-Verhoog** [comment]
Hi @eedwards-sk,

Sorry for the delay on this.

I tried to reproduce with this really small app here: https://github.com/DataDog/trace-examples/pull/79/files

```
ddtrace==0.26.0
celery==4.1
redis==2.10.6
kombu==4.1.0
```

this example reports traces without any issue.

Do you have the same symptoms from #451? Specifically the one where the patching for celery is failing? ie when run with the environment variable `DATADOG_TRACE_DEBUG=true`, you don't see `celery` in the line

```
2019-10-17 21:26:45,604 INFO [ddtrace.monkey] [monkey.py:140] - patched 5/30 modules (celery,flask,redis,requests,sqlite3)
```

in the logs.

**Comment by eedwards-sk** [comment]
Hi @Kyle-Verhoog 

As per #451, both the original issue I reported, and my most recent [comment](https://github.com/DataDog/dd-trace-py/issues/451#issuecomment-517369760) (from right before I opened this issue) confirmed that celery was present in the list of patched modules.

The issue seems to be that autodiscovered tasks are not being instrumented.

**Comment by Kyle-Verhoog** [comment]
Ah darn I read just about all of the #451 thread except for the last comment! Sorry about that.

Hmm. Very strange as the celery integration works via celery signals (should be task independent) and the celery integration hasn't been touched functionality-wise since v0.20.1.

Maybe it's some interference from Django. I'll try looking through our changelog for anything noticeable around v0.26. Is the tracing working prior to v0.26?

**Comment by eedwards-sk** [comment]
@Kyle-Verhoog 

We have one project that was working on `ddtrace==0.18.0` and then we bumped it to `0.26.0`.

We have another almost identical django/celery project that we started on `0.26.0` so it also isn't working (for autodiscovered celery tasks).

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk gotcha, thanks for the context & quick replies. The version info should help narrow down the search 🙂.

I forgot to ask earlier, how are you running your celery workers? (Is it still the same as https://gist.github.com/eedwards-sk/f924548c043859901db6918aec95dada?)

I have a suspicion that Django might be interfering somehow. What Django version(s) are you running and with which wsgi server + version?

Hopefully this should be enough info to stop bugging you (for now 😛)!

**Comment by eedwards-sk** [comment]
@Kyle-Verhoog 

Here's basically what it's running with:

```
export DATADOG_ENV="stage"
export DATADOG_SERVICE_NAME="spice-worker"
export DATADOG_TRACE_ENABLED="true"
export DATADOG_STATSD_HOST="${ecs_host_ip}"
export DATADOG_TRACE_AGENT_HOSTNAME="${ecs_host_ip}"
exec ddtrace-run celery -A snap_spice worker
```

for packages, we're not running the celery workers using a wsgi server, so I'm not sure if these versions matter, but in case...

```
Django==2.2.5
gunicorn==19.9.0
gevent==1.4.0
```

I can confirm the service (`spice-worker`) does occasionally show up for a non-autodiscovered task, just like when we had this symptom before.

e.g. this address should work if you can impersonate our account
```
https://app.datadoghq.com/apm/service/spice-worker/celery.run?end=1571367047568&env=stage&paused=false&start=1568775047568
```

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk perfect!

Thanks for your patience as well as the quick, detailed and concise responses. We'll dig into this further with all the info you've provided and get back to you as soon as possible with our findings 😄.

**Comment by yamaszone** [comment]
Any update on this? We need a fix for this urgently.

**Comment by Kyle-Verhoog** [comment]
@shuvozula thanks for the report. The evidence does appear to be pointing towards Django. Are you also using shared tasks?

@yamaszone I have it on my todo list for this week. Are you also using Django (and celery shared tasks)?

**Comment by shuvozula** [comment]
yes @Kyle-Verhoog , we are using shared tasks for Celery functions

**Comment by shuvozula** [comment]
Hi @Kyle-Verhoog, @yamaszone and myself are from the same team, so we're referring to the same issue

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk @shuvozula finally got a chance to do some digging.

There haven't been changes to either the celery or the django integration that would seem to cause this from what I can tell.

However, my bet right now is that the changes to the writer (introduced in **`v0.26`**) broke our handling of forking (which I believe celery workers do to run the task). This bug was uncovered just recently in  #1102 and #1103. It was fixed in #1106 and [released](https://github.com/DataDog/dd-trace-py/releases/tag/v0.30.2) a couple days ago in `v0.30.2`.

Would you be able to try out `v0.30.2` to see if this resolves the issue?

**Comment by shuvozula** [comment]
Hi @Kyle-Verhoog, actually didn't have any luck with `v0.30.2` either. I was watching [1102](https://github.com/DataDog/dd-trace-py/issues/1102) and within the hour `v0.30.2` was released, I tested it but the celery-spans never showed up.

**Comment by Kyle-Verhoog** [comment]
@shuvozula hmmm. Based off of the info you've sent us through support it looks like you're getting the first part of the distributed celery trace reported correctly but not the receiving part from the worker. Does your container which you're running celery workers have access to a Datadog agent?

**Comment by eedwards-sk** [comment]
Lol, GitHub closed this issue automatically when I referenced it from an internal PR.

Re-Opened.

I've bumped to `0.30.2` and I'll check tomorrow to see if we get the expected traces.

**Comment by Kyle-Verhoog** [comment]
You got me all excited that the issue was resolved! 😆

**Comment by eedwards-sk** [comment]
Well unfortunately `0.30.2` did not resolve it for me, either.

I'm seeing the service + traces for our celery beat scheduler and the django web app, but still none for the celery worker.

**Comment by shuvozula** [comment]
Pretty sure the Celery workers have access to the Datadog agent, verified from some debugging logging that `tracer.configure()` is connecting to the same agent host as the Django app (Django-Rest-Framework actually). But I'm not sure how to verify if the agent is receiving the spans from Celery (checked agent log messages)

**Comment by brettlangdon** [comment]
Would someone be able to run their celery worker with debug logging enabled for us?

If you are using `ddtrace-run`, you can set `DATADOG_TRACE_DEBUG=true` and `DD_LOGGING_RATE_LIMIT=0` environment variables.

If you are not using `ddtrace-run`, you can configure via code:

```python
import logging

logging.getLogger('ddtrace').setLevel(logging.DEBUG)
# or
logging.basicConfig(level=logging.DEBUG)
```

But will still need to set `DD_LOGGING_RATE_LIMIT=0` environment variable.

If you do not wish to share the logs here, you can email to both myself and Kyle (brett.langdon@datadoghq.com and kyle.verhoog@datadoghq.com).

A few things:

1) The `DD_LOGGING_RATE_LIMIT=0`, by default the loggers our tracers use are rate limiter (this is why you might see `, skipped X additional messages` in your logs. We do this to reduce any potential spammy nature if an error or log message happens in a hot path. Setting to `0` will disable so we can see everything

2) What this debug logging will hopefully give us.

It will pretty print every trace that is generated to the logger when it gets pushed into the background worker for flushing.

This will tell us that the tracer is indeed successfully producing traces, and we can spot check them for any potential errors.

We will also get some log messages for flushes to the agent, can verify that they are indeed making it to the agent.

If we do not see any traces in the logs, it means either a) instrumentation is not setup, traces are not being started, or b) traces are not finishing, if the root span doesn't finish, then it'll just stay in memory forever and never close and flush.


There is definitely a chance that these debug logs don't point to anything clear, but since we are having trouble reproducing this on our end I think it is worth while to grab just to double check that everything looks ok and healthy to narrow down the scope of where we are looking to reproduce.

**Comment by eedwards-sk** [comment]
@brettlangdon I can definitely do that, but our logs are currently shipped to Datadog :) what is the best way to share them?

**Comment by brettlangdon** [comment]
@eedwards-sk you can send me a link to Log Explorer if they are showing up in there.

Or I am guessing I can search `level:DEBUG` and `"ddtrace"` to probably find them, but I didn't see anything yet so just let me know and I can probably go spelunking for them :)

**Comment by eedwards-sk** [comment]
Deploying Now, you should see debug logs show up from the worker here shortly:

```
https://app.datadoghq.com/logs?cols=&event&from_ts=1571953644720&index=main&live=true&messageDisplay=expanded-md&query=app.project.name%3Aspice+service%3Aspice-worker+app.environment.name%3Astage&stream_sort=desc&to_ts=1571954544720
```

**Comment by eedwards-sk** [comment]
I've reverted the debug logging. You won't see much in the logs. That app has extremely infrequent celery jobs.

We have another project that also uses celery 4.x and is having the same issue, but it doesn't run in a stage environment.

I'm a bit hesitant to enable debug logging in production.

**Comment by brettlangdon** [comment]
Yeah, I don't really see anything in there, would ideally need debug logging when a job gets processed.

For debug logging, it'll really just make a bunch of noise, pretty harmless, but I also totally understand the hesitation to enable in production.

Do you happen to have this same problem when you run the celery worker locally/in dev?

**Comment by eedwards-sk** [comment]
I don't have a good way to test it locally or in dev either. Long story.

I will try and enable it in production.

**Comment by brettlangdon** [comment]
@eedwards-sk how often does this worker run jobs?

I decided to manually navigate to the service page for it... and I do actually see some traces, but there is like 1 every few days only (6 traces over the last month).

https://app.datadoghq.com/apm/service/spice-worker/celery.run?end=1571956113819&env=prod&paused=false&start=1569364113819

(also heads up, sort of past EOD for me, so I might trail off here)

**Comment by eedwards-sk** [comment]
That app should have daily jobs, but some stuff is likely infrequent.

The other app I'm enabling debug on now is actually the one we feel the pain point with and it runs jobs frequently.

**Comment by eedwards-sk** [comment]
Also to be clear, the issue was never that we aren't getting ANY traces. As I've said a few times, I proved the app is getting instrumented properly and can send traces. The issue seems to be with autodiscovered tasks (or similar).

**Comment by eedwards-sk** [comment]
Here you go:

```
https://app.datadoghq.com/logs?cols=&from_ts=1571953897877&index=main&live=false&messageDisplay=expanded-md&query=app.project.name%3Acrm+service%3Acrm-worker+app.environment.name%3Ainfra&stream_sort=desc&to_ts=1571957497877
```

This project invokes worker tasks every 10 minutes at a minimum. These logs show the startup of the app with celery being instrumented, but no trace output when the tasks run, and no traces.

**Comment by shuvozula** [comment]
Here's mine:
```
https://app.datadoghq.com/apm/traces?end=1571997296177&env=dev&index=apm-search&paused=false&routing_hint=1571996397372&service=logflights-celery-producer&spanID=5207073771147509781&start=1571993696177&traceID=16757735186311154147
```

**Comment by Kyle-Verhoog** [comment]
Phew, thank you both with your patience and willingness to help with debugging this pesky issue!

I think I'm **finally** able to reproduce it on my end. Like you said @eedwards-sk, it does seem to be related to only shared tasks, but I couldn't reproduce unless it was in a Django app. Going to drill down into it now and hopefully find the problem.

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk (I think you're already aware of this), @shuvozula note that `ddtrace` will disable itself if you have `DEBUG=false` in your Django `settings.py`. This will happen even for celery workers since celery pulls in Django settings when looking for workers (and then `ddtrace` reads the Django settings when auto-patching Django).

This is one complication I had when trying to reproduce. I didn't realize that celery would initialize the Django settings and then result in a disabled tracer.

**Comment by eedwards-sk** [comment]
@Kyle-Verhoog Thanks for chasing down a repro!

If at all possible, please add our use case to your regression testing.

It would be very helpful for us to ensure this functionality does not break again, once you fix it :)

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk we had success some success with #1102. Would you be able to try it out as well?

`pip install -e git+https://github.com/datadog/dd-trace-py@celery/strongref#egg=ddtrace`

(Also, be sure either the `django` integration is disabled or `DEBUG=True` (in `settings.py`) for the celery worker so that the tracer doesn't get disabled.)

Hopefully this addresses the problem!

**Comment by eedwards-sk** [comment]
Sorry, was on vacation.

I'm happy to test a new official release, but since we don't have an easy repro outside of production, I am not comfortable testing with a custom branch that has not been accepted.

Rather than rely on me to test the release, it would be better if you had a proper regression test that exercises this behavior, so you can release it with confidence, and so we can continue to take upgrades from datadog without losing core functionality.

**Comment by eedwards-sk** [comment]
Hi,

Any updates on this?

**Comment by eedwards-sk** [comment]
@Kyle-Verhoog @brettlangdon I just got confirmation from our rep that this was released.

Can we please close the ticket to reflect as much?

I will be testing the release shortly.

I was disappointed to discover the fix was released and no-one came here to help inform everyone who has been waiting for it. It's been almost 4 months without celery APM now.

**Comment by Kyle-Verhoog** [comment]
Hi @eedwards-sk,

@shuvozula confirmed that #1122 fixed their celery issue and it was included in `v0.31.0` late last week.

My apologies for not updating the thread when that went out. I want to keep this issue open until it is confirmed to be resolved for you as it's not clear whether it's the same issue that you're experiencing or not.

**Comment by eedwards-sk** [comment]
I've installed and deployed `0.31.0` to our single-environment production application which was exhibiting the problem.

We are now seeing requests show up (so our "celery worker" does now show up in the services list), but we are not yet receiving any traces:

https://app.datadoghq.com/apm/resource/crm-worker/celery.run/527d881f8a562742?end=1574282109033&env=infra&index=apm-search&paused=false&start=1574278509033&routing_hint=1574282056785&spanID=12530329313888530780

I will continue to monitor to see if any traces show up over time.

**Comment by eedwards-sk** [comment]
We're still failing to get any traces. So while the tasks are now being discovered, it's not generating the expected traces.

**Comment by eedwards-sk** [comment]
We got [one trace](https://app.datadoghq.com/apm/resource/crm-scheduler/celery.apply/527d881f8a562742?end=1574290760124&env=infra&index=apm-search&paused=false&start=1574287160124&event=AQAAAW6K5p7MkKohVwAAAABBVzZLNXExY0lJVWRHS1FNOXFRaQ&traceID=2513783439868597393&spanID=519773721689015963&routing_hint=1574288400076) to show up on the celery scheduler (celery beat).

No traces for the celery worker tasks yet.

In addition, with the frequency of the current task executions, I wouldn't expect any kind of sampling to affect it -- meaning I would currently expect a trace for each request.

However, there's some asynchronous temporal load on this service, so I will observe it for a couple more days in hopes of seeing some traces.

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk thanks for the updates, I checked on your account and see the same. The service is there but no traces. Very strange as I don't think they should be sampled either.

I'm investigating further to see why this might be happening.

**Comment by Kyle-Verhoog** [comment]
@eedwards-sk after some investigation our best guess is that they did get sampled out. If you could update your agent to the latest version as we've included some metrics related to sampling that would assist in confirming that the traces were indeed sampled out.

Hopefully we'll see in the next couple days!

**Comment by eedwards-sk** [comment]
Hey @Kyle-Verhoog I pushed new docker hosts with the latest datadog agent into production last night.

I am seeing traces for the worker tasks, which is great news.

I'm going to close the issue and will open a follow-up if I notice sampling issues.

To conclude, I beg of you, as you're authors of a product that we're paying for, to do the work necessarily to set up automated regression testing for this use case. For the amount of money APM costs us, and your other customers, it is unacceptable to have core functionality become broken for 4 months because you're not testing the use cases that your product offers. Please take this as an opportunity to improve your automated test coverage.
