### ISSUE TITLE
Django patch for as_view() breaks dispatch() call chain

### ISSUE THREAD

**Issue by rickhutcheson** [DataDog/dd-trace-py#1623]
### Which version of dd-trace-py are you using? 

0.41 (but master also affected)

### How can we reproduce your problem?

_**NOTE:** This description is mostly copied from @rbusquet, who had a (now deleted) [repository to reproduce the bug](https://github.com/rbusquet/ddtrace-inheritance-bug
). I found it while searching for related concerns on the web._

In the current version of ddtrace, the django patch **inserts custom `dispatch()` methods** into the View hierarchy, breaking existing code. 

We can easily see the behavior using `TemplateView`, but any view used in the same way can trigger the behavior.

#### Step 1: Use TemplateView directly in some urls file.

```
urlpatterns = [
    path("some-static-view/", TemplateView.as_view(template_name='my-template.html'))
]
```

DataDog's ddtrace instruments views by patching the `as_view` function. With the example above, we can see the patch being applied in the following points:

1. The patch will try to find a dispatch (amongst others) method in the view class where we're calling as_view
1. This will return `django.views.View.dispatch`. `TemplateView` does not implement it, so it will grab the parent class' implementation
1. After instrumenting dispatch, ddtrace assigns the wrapped version of dispatch to the instance. That's important. In the example we're seeing, that'd be `TemplateView`
1. `TemplateView` now has a `dispatch` method, that consists of a wrapped version of django's `View.dispatch`.

That's fine by itself, but issues occur when another class then wants to _extend_ `TemplateView`. 

#### Step 2: Mix TemplateView with another View subclass w/ dispatch()

Let's suppose later in the interpretation path the following views are implemented:

```
from django.views.generic import TemplateView, View as DjangoView

class CustomDispatchView(DjangoView):
    def dispatch(self, request):
        print('Custom dispatch called!')
        super().dispatch(self, request)


class ComposedView(TemplateView, CustomDispatchView):
    template_name = 'custom.html'
```

Without ddtrace,` ComposedView.dispatch` will be `CustomDispatchView.dispatch`.

But if we're using `ddtrace` and `TemplateView.as_view` was *ever* called before the classes above were interpreted, `TemplateView` now HAS a dispatch member defined. `ComposedView.dispatch` will be the new, patched, `TemplateView.dispatch` method, and `'Custom dispatch called!'` will not be printed.

### What is the result that you get?

Views without a `dispatch()` method have one added, breaking existing code.

### What is the result that you expected?

I'd expect for `dispatch()` not to be inserted in this way, and only overridden for classes that _actually define it_, or search the MRO until a definition is found.

**Comment by brettlangdon** [comment]
Hey @rickhutcheson thank you for reporting this issue. This issue is resolved by #1622 and will be released in the next version of the `ddtrace` package.

If you'd like to try out the change before the release you can install our package from GitHub via:

```
pip install git+https://github.com/DataDog/dd-trace-py#egg=ddtrace
```

We will notify here once the release goes out. If you have any other issues, please do not hesitate to let us know!

**Comment by brettlangdon** [comment]
`0.41.1` has been released which resolves this issue.

**Comment by rickhutcheson** [comment]
@brettlangdon thanks for reaching out!

I just checked, and sadly, I don't think it is resolved. 😕 

#### In version from git+https://github.com/DataDog/dd-trace-py#egg=ddtrace
```
[REC] In [1]: from django.views.generic.base import View, TemplateView

[REC] In [2]: 'dispatch' in TemplateView.__dict__
Out[2]: True
```

#### In version 0.30.0 (Our current version)
```
[REC] In [1]: from django.views.generic.base import View, TemplateView

[REC] In [2]: 'dispatch' in TemplateView.__dict__
Out[2]: False
```

Additionally, I'm still seeing the behavior in which our custom `dispatch()` is bypassed.

I think that's because the patch still calls `wrap` (aka `wrap_function_wrapper`) **on TemplateView itself**, and wrapt still does a `setattr` on the `TemplateView`. It's not clear to me whether this is a bug in wrapt..

My only thought around solving the problem is to instead have the patch look up the MRO and call `wrap()` on the first parent that actually defines the method. WDYT?

**Comment by brettlangdon** [comment]
@rickhutcheson thank you for raising, we are digging into this right away.

**Comment by rbusquet** [comment]
https://github.com/DataDog/dd-trace-py/pull/1615/ had this fixed but looks like it was reverted. 0.41.1 failing in my tests and the issue is still present.

**Comment by brettlangdon** [comment]
@rickhutcheson and @rbusquet thank you both for confirming this.

We are going to reintroduce #1615 as a bugfix as soon as we can.

We thought the test cases we added to our test suite properly covered this case so were trying to find a smaller/more isolated fix for the issue. However, it appears the test case we added to our suite doesn't properly trigger this issue.

We will update here as we release a new update for this issue.

**Comment by brettlangdon** [comment]
@rickhutcheson and @rbusquet we have opened #1625 which introduces #1615, along with more test coverage that better enforces this behavior, and stresses the proper resolution.

Feel free to try this version out, but the core changes are the same from #1615 that @rbusquet previously confirmed as a fix.

We will update here as soon as we release a new package version with this change.

**Comment by brettlangdon** [comment]
@rickhutcheson sorry for not replying to this directly before.

> My only thought around solving the problem is to instead have the patch look up the MRO and call wrap() on the first parent that actually defines the method. WDYT?

Yeah, we agree with this statement. Exactly what we are thinking as well. We want to get #1625 changes out quickly since they solve this particular issue then we want to go back and rethink how we are using wrapt for patching across the entire repo (we think these cases are isolated, but still better to be 100% sure).

**Comment by brettlangdon** [comment]
v0.41.2 is released with the change from #1625.

Please let us know if you continue to experience any issues.

**Comment by rickhutcheson** [comment]
@brettlangdon Thank you so much! The issue has been resolved =]
