### ISSUE TITLE
patch() errors out for pymongo 4.5.0

### ISSUE THREAD

**Issue by mapuri** [DataDog/dd-trace-py#7325]
### Summary of problem
patch() errors out for pymongo 4.5.0 but works for previous release 4.4.1

### Which version of dd-trace-py are you using?
ddtrace (1.18.0) but error appears to persist when I updated ddtrace to 2.1.1

### Which version of pip are you using?
$pip3 --version
pip 23.1.2

### Which libraries and their versions are you using?

<details>
  <summary>`pip freeze`</summary>
  
$pip3 freeze
aiofiles @ file:///Users/***/Library/Caches/pypoetry/artifacts/ca/ba/fe/ee94fb965d1491f9578e5f28e8c6f0ae62e5af1e20faedc39b93b44d72/aiofiles-0.8.0-py3-none-any.whl
aiohttp==3.8.5
aiosignal==1.3.1
anyio @ file:///Users/***/Library/Caches/pypoetry/artifacts/0c/36/3c/de83f6f0d02cc7a0320ef0052e2a119f333cfe9a4d3c64f48df7f8d685/anyio-3.6.2-py3-none-any.whl
APIFlask==1.2.3
apispec==6.3.0
appnope==0.1.3
astor @ file:///Users/***/Library/Caches/pypoetry/artifacts/09/5c/54/37b579cdfe7b1a219f41cb5d12fde801593f9c600ce5bee29dfe931626/astor-0.8.1-py2.py3-none-any.whl
asttokens==2.2.1
async-timeout==4.0.3
attrs==23.1.0
autoflake @ file:///Users/***/Library/Caches/pypoetry/artifacts/0a/e2/88/403193f3f1a7ff5762c5f3f9e4e6b6d386ebd4f0390bab2eb778cd36cd/autoflake-1.7.8-py3-none-any.whl
backcall==0.2.0
bandit @ file:///Users/***/Library/Caches/pypoetry/artifacts/f0/49/b5/f7eef3f37396c309ab2b6498c81d9ab34d2d1734c1831218a4f2603023/bandit-1.7.4-py3-none-any.whl
black==23.7.0
boto3==1.28.30
botocore==1.31.30
Brotli==1.0.9
build==0.10.0
bytecode==0.14.2
CacheControl==0.12.11
cachy==0.3.0
cattrs==23.1.2
certifi==2023.7.22
cffi==1.15.1
cfgv @ file:///Users/***/Library/Caches/pypoetry/artifacts/35/10/a3/f57b5e70e8b5d5f31bccdd15df3781efda09dc1b44b473591e360c20e5/cfgv-3.3.1-py2.py3-none-any.whl
charset-normalizer==3.2.0
circuitbreaker==1.4.0
cleo==2.0.1
click==8.1.7
clikit==0.6.2
comm==0.1.4
commonmark==0.9.1
confluent-kafka==2.2.0
coverage==5.5
crashtest==0.4.1
cryptography @ file:///Users/***/Library/Caches/pypoetry/artifacts/60/49/d4/3f0688c529c339309b802c9e606d0bcd0d4003959de7064dc491c94928/cryptography-38.0.4-cp36-abi3-macosx_10_10_x86_64.whl
databricks-cli==0.17.4
ddsketch==2.0.4
ddtrace==1.18.0
debugpy==1.6.7.post1
decorator==5.1.1
Deprecated==1.2.14
distlib==0.3.6
dnspython==2.4.2
docutils @ file:///Users/***/Library/Caches/pypoetry/artifacts/49/06/62/0ad22e5dcbb2b9b2766963b30e3829d6081e9e68fccbab17e9e62b6c80/docutils-0.19-py3-none-any.whl
dulwich==0.21.5
entrypoints @ file:///Users/***/Library/Caches/pypoetry/artifacts/15/89/41/13ff23013f003f094ddfbd2347d7275f294139b11a6762447ad83ce465/entrypoints-0.4-py3-none-any.whl
envier==0.4.0
eradicate @ file:///Users/***/Library/Caches/pypoetry/artifacts/60/be/db/8813e0e3bde9cd1fbe282ee0d5e3dcb5952e9a414b9877b9d7768bcc93/eradicate-2.1.0-py3-none-any.whl
exceptiongroup==1.1.3
executing==1.2.0
fastapi @ file:///Users/***/Library/Caches/pypoetry/artifacts/b3/66/14/e68b3465f834555c09cf32d44f80b8a4ff3d3161a3b4518bbf03ce1799/fastapi-0.88.0-py3-none-any.whl
fastapi-utils @ file:///Users/***/Library/Caches/pypoetry/artifacts/f2/8e/e9/89ee940063ed6992416c6eb03a798f15da800bb3a15d4697438cbc2a3c/fastapi_utils-0.2.1-py3-none-any.whl
filelock==3.8.0
flake8==5.0.4
flake8-polyfill @ file:///Users/***/Library/Caches/pypoetry/artifacts/94/ed/18/a0bf327df9a14974261491aee203f5a18f9d02dcabf28e5fc17c480a98/flake8_polyfill-1.0.2-py2.py3-none-any.whl
Flask==2.2.2
Flask-Compress==1.13
Flask-Cors==3.0.10
Flask-HTTPAuth==4.8.0
Flask-Limiter==2.9.2
flask-marshmallow==0.15.0
fluyt==0.1.0
frozenlist==1.4.0
gevent==21.12.0
gitdb @ file:///Users/***/Library/Caches/pypoetry/artifacts/0f/d4/af/f7f82c01c8da62ecaddb9b40a1bba91a8c4a03003152ef25dd99da8372/gitdb-4.0.10-py3-none-any.whl
GitPython @ file:///Users/***/Library/Caches/pypoetry/artifacts/85/9d/30/107c003de234c5c2e14eb81dd599fe984b51ad5436973dd2f5df5d3c36/GitPython-3.1.29-py3-none-any.whl
graphql-core==3.2.3
greenlet==1.1.3.post0
gunicorn==20.1.0
h11 @ file:///Users/***/Library/Caches/pypoetry/artifacts/9a/ce/16/adb43d44234e45608e12ef4254873fa6a1749ab0d28c5933fb1acbc4a3/h11-0.12.0-py3-none-any.whl
html5lib==1.1
httpcore @ file:///Users/***/Library/Caches/pypoetry/artifacts/43/4e/9f/3b2d668cc25956d120bcd1854bc1f43b5edb2bf88227a1c40ec96402a3/httpcore-0.15.0-py3-none-any.whl
httptools @ file:///Users/***/Library/Caches/pypoetry/artifacts/0d/3d/97/262e6ec2f22acb36e49cad38cad0e7e0ef7f45832ee9d744c87a8937f5/httptools-0.3.0-cp310-cp310-macosx_10_9_x86_64.whl
httpx @ file:///Users/***/Library/Caches/pypoetry/artifacts/62/62/35/11a4e336f5eea8be8b6859e1a90718b76f389c5ed378519815ea305188/httpx-0.23.0-py3-none-any.whl
hypothesis==6.82.5
identify @ file:///Users/***/Library/Caches/pypoetry/artifacts/a1/1a/e4/793aa03f0bf3c4c020c773dd604f003d709160dfd89db8ccfa71e959a2/identify-2.5.9-py2.py3-none-any.whl
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.1
iniconfig==2.0.0
installer==0.7.0
ipykernel==6.25.1
ipython==8.14.0
isort @ file:///Users/***/Library/Caches/pypoetry/artifacts/12/e3/f1/e8e484225dcc659de6e4ac34a4ad996cb71f36119e54e71462cc7ad7e8/isort-5.10.1-py3-none-any.whl
itsdangerous==2.1.2
jaraco.classes==3.2.2
jedi==0.19.0
Jinja2==3.1.2
jmespath==1.0.1
jsonschema==4.19.1
jsonschema-specifications==2023.6.1
jupyter_client==8.3.0
jupyter_core==5.3.1
keyring==23.13.1
limits==3.5.0
llvmlite==0.39.1
lockfile==0.12.2
loguru @ file:///Users/***/Library/Caches/pypoetry/artifacts/36/1f/fa/e70e76ec49384e6de44a56eedd13608349891af6858a468e0f06d336a5/loguru-0.6.0-py3-none-any.whl
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib-inline==0.1.6
mccabe==0.7.0
more-itertools==9.1.0
moto @ file:///Users/***/Library/Caches/pypoetry/artifacts/d6/09/cc/0361341c4864dc902f884d4cc1f006bb58aae8774fe972c77251a9c3f9/moto-3.1.18-py3-none-any.whl
msgpack==1.0.4
multidict==6.0.4
mypy @ file:///Users/***/Library/Caches/pypoetry/artifacts/d2/8f/1b/3ca5cb8a1cbc5c089d76fbf83f51134324f435e4ee77569165d5e7267a/mypy-0.961-cp310-cp310-macosx_10_9_x86_64.whl
mypy-extensions==1.0.0
nest-asyncio==1.5.7
nodeenv @ file:///Users/***/Library/Caches/pypoetry/artifacts/f2/32/85/8e58087fd2e35edc6c633a3087db5b66d7d1f313aa2a9a6a8eeb5c22f0/nodeenv-1.7.0-py2.py3-none-any.whl
numba==0.56.4
numpy==1.23.5
oauthlib==3.2.2
opentelemetry-api==1.19.0
ordered-set==4.1.0
packaging==23.1
pandas==1.5.3
parso==0.8.3
pastel==0.2.1
pathspec==0.11.2
pbr @ file:///Users/***/Library/Caches/pypoetry/artifacts/1a/4b/06/eafed158d794b75c9549557a679b58cf09f63f6096d92dddb5fa447082/pbr-5.11.0-py2.py3-none-any.whl
pexpect==4.8.0
pickleshare==0.7.5
pkginfo==1.9.6
platformdirs==2.6.2
pluggy==1.2.0
poetry==1.4.2
poetry-core==1.5.2
poetry-plugin-export==1.3.1
pre-commit @ file:///Users/***/Library/Caches/pypoetry/artifacts/1a/58/60/20b6ce392b5caffa7d8abd4d5b0dcc22027353e28b2d7533ae995a7fee/pre_commit-2.20.0-py2.py3-none-any.whl
prompt-toolkit==3.0.39
protobuf==4.24.1
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
py4j==0.10.9.5
pycodestyle==2.9.1
pycparser==2.21
pycryptodome==3.18.0
pydantic @ file:///Users/***/Library/Caches/pypoetry/artifacts/7e/d7/47/3040f8f317962a00218fdc093e7b86e776e025f05c86bb71930c6c3974/pydantic-1.10.2-cp310-cp310-macosx_10_9_x86_64.whl
pydocstyle @ file:///Users/***/Library/Caches/pypoetry/artifacts/76/51/27/5fedbe9b911687054391ee48811ebde649f80f6f5833a6f2c00c896338/pydocstyle-6.1.1-py3-none-any.whl
pyflakes==2.5.0
Pygments==2.16.1
PyJWT==2.6.0
pylev==1.4.0
pymongo==4.5.0
pymongo-auth-aws==1.1.0
pynamodb @ file:///Users/***/Library/Caches/pypoetry/artifacts/36/ba/f1/9f78525de85122a2c7ed0326d24cc2f86b8560db1dd221d739c259f099/pynamodb-5.3.3-py3-none-any.whl
pyparsing @ file:///Users/***/Library/Caches/pypoetry/artifacts/e1/09/c0/6a6df3ef412eb19fcda1b353ea54e3b48f9c518348fadd0967a962cbb6/pyparsing-3.0.9-py3-none-any.whl
pyproject_hooks==1.0.0
pyrsistent==0.19.3
pyspark==3.3.1
pytest==7.4.0
pytest-asyncio @ file:///Users/***/Library/Caches/pypoetry/artifacts/82/9d/70/c77b2e737b2c00b41a3144a3686b082a8c6775e7f920b01ecae86e9bee/pytest_asyncio-0.19.0-py3-none-any.whl
pytest-cov @ file:///Users/***/Library/Caches/pypoetry/artifacts/a3/4c/ca/234bf6c69d192516716a1fec5b61b6329bb00e1d33529113864b1db4eb/pytest_cov-3.0.0-py3-none-any.whl
pytest-env @ file:///Users/***/Library/Caches/pypoetry/artifacts/9e/cb/c2/927d0f2d6698b9eb6930236b69c9808464eb347807d14a08fb8f4ecdd7/pytest-env-0.6.2.tar.gz
python-dateutil==2.8.2
python-dotenv @ file:///Users/***/Library/Caches/pypoetry/artifacts/95/ad/17/e8d041284e9275b58ae8e27059a863baf740c9f7ebafb0713fa9bc4e24/python_dotenv-0.21.0-py3-none-any.whl
python-ulid @ file:///Users/***/Library/Caches/pypoetry/artifacts/b4/f3/82/b283a25e472da85a8c6f3ba2b2872804af68584563977081d9dbe6b00f/python_ulid-1.1.0-py3-none-any.whl
pytz==2022.7.1
PyYAML @ file:///Users/***/Library/Caches/pypoetry/artifacts/ff/26/48/6836dedef41c8baa75efc633d5aada6c1274e95f36425a7c822e240c51/PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl
pyzmq==25.1.1
rapidfuzz==2.15.1
redis==3.5.3
redis-py-cluster==2.1.3
referencing==0.29.1
requests==2.31.0
requests-futures==1.0.1
requests-mock==1.11.0
requests-toolbelt==0.9.1
responses @ file:///Users/***/Library/Caches/pypoetry/artifacts/89/00/27/9ce9f28d57af2ee49e849095c197a6df1f68304f7a64f7f599bd8ca6d3/responses-0.22.0-py3-none-any.whl
respx @ file:///Users/***/Library/Caches/pypoetry/artifacts/56/08/c1/b14152c98ada1d0174f5eae4ed9ba7d5601a8cde1507421c45fb1650fc/respx-0.19.3-py2.py3-none-any.whl
restructuredtext-lint @ file:///Users/***/Library/Caches/pypoetry/artifacts/81/bc/84/e389fe50ba4ac624a1658aed8cdcceb18a58f785c459c2c067edeb7af5/restructuredtext_lint-1.4.0.tar.gz
rfc3986 @ file:///Users/***/Library/Caches/pypoetry/artifacts/11/74/da/f15a8d7ababda7a021d73f0f9ca94181607fe7c7366942c2c58cf30e65/rfc3986-1.5.0-py2.py3-none-any.whl
rfeatureclient==0.2.0
rich==12.6.0
rpds-py==0.8.11
s3transfer==0.6.2
shellingham==1.5.0
six==1.16.0
smmap @ file:///Users/***/Library/Caches/pypoetry/artifacts/c9/39/91/ed6e3da1cbfcb68393f3640f3d84c7afd8574257495adb1fe2615bbeaa/smmap-5.0.0-py3-none-any.whl
sniffio @ file:///Users/***/Library/Caches/pypoetry/artifacts/c9/3f/3e/8e46c9457f352d5bba461491356dfede8138f565b9e1015719034b36a1/sniffio-1.3.0-py3-none-any.whl
snowballstemmer @ file:///Users/***/Library/Caches/pypoetry/artifacts/c4/88/1b/a9b3e7fb8e193ad3ed607c754eb234b06cbd6f0a43289406a2dc4eddbf/snowballstemmer-2.2.0-py2.py3-none-any.whl
sortedcontainers==2.4.0
SQLAlchemy @ file:///Users/***/Library/Caches/pypoetry/artifacts/6d/d3/fd/845bd61cdee143ff539aba25f8493e14d765a9f3e74e01a2679259cda3/SQLAlchemy-1.4.44-cp310-cp310-macosx_10_15_x86_64.whl
stack-data==0.6.2
starlette @ file:///Users/***/Library/Caches/pypoetry/artifacts/23/50/64/3573df8b238414705347a7deb53f368896314de2ca2e6db0ae218ea337/starlette-0.22.0-py3-none-any.whl
stevedore @ file:///Users/***/Library/Caches/pypoetry/artifacts/5f/3d/ce/fb433118ce565133b9de58c724e7ae929b26f93cca07e8b497b8e2cc8e/stevedore-4.1.1-py3-none-any.whl
strawberry-graphql==0.171.3
tabulate==0.9.0
tenacity==8.2.2
tokenize-rt @ file:///Users/***/Library/Caches/pypoetry/artifacts/95/75/c3/3608c731d87fa46749b1a1b107712236510c372052455b6a465690190b/tokenize_rt-5.0.0-py2.py3-none-any.whl
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.4
tornado==6.3.3
traitlets==5.9.0
trove-classifiers==2023.5.2
types-toml @ file:///Users/***/Library/Caches/pypoetry/artifacts/64/45/c0/dddbb51bcc07776408b0e3fdc485f32ff638983fdaa4a6055c2036e32d/types_toml-0.10.8.1-py3-none-any.whl
typing_extensions==4.7.1
ujson @ file:///Users/***/Library/Caches/pypoetry/artifacts/03/a3/43/c6bb256eb29f38b90bc9592b9e5c7b8f34463f42315b4d448e29a9bc0f/ujson-5.5.0-cp310-cp310-macosx_10_9_x86_64.whl
urllib3==1.26.16
uvicorn @ file:///Users/***/Library/Caches/pypoetry/artifacts/21/cc/1d/812355b7ae438821f8e78fade0b6fbd87d7d4ab025a7e7845a258809c8/uvicorn-0.17.5-py3-none-any.whl
uvloop @ file:///Users/***/Library/Caches/pypoetry/artifacts/68/7a/c9/f73d27d0a315ab001a1a67fff5a2aaac89a62a3f8f90302cc33aedd45f/uvloop-0.17.0-cp310-cp310-macosx_10_9_x86_64.whl
virtualenv @ file:///Users/***/Library/Caches/pypoetry/artifacts/09/3d/32/06580acc9d7f1a1651a8d5c583e1d3a6e071e9147ffb4e2e9d2140d8a8/virtualenv-20.17.0-py3-none-any.whl
watchgod @ file:///Users/***/Library/Caches/pypoetry/artifacts/c9/6e/db/33a42b730360863b7d6e70032cd526b1ceb936dceb811afadedf6854c9/watchgod-0.8.2-py3-none-any.whl
wcwidth==0.2.6
webargs==8.3.0
webencodings==0.5.1
websockets @ file:///Users/***/Library/Caches/pypoetry/artifacts/6d/21/fb/bafa726ce22ff8a8e4f9972555eaf6ef903cbc5fc9e7785e9eec2862d0/websockets-10.4-cp310-cp310-macosx_10_9_x86_64.whl
Werkzeug==2.3.7
wrapt==1.15.0
xattr==0.10.1
xmltodict==0.13.0
yapf @ file:///Users/***/Library/Caches/pypoetry/artifacts/43/67/9f/da3c8e46f9596653136ce94a345d24c0ad4f4ae8ed02e15876765e7f81/yapf-0.32.0-py2.py3-none-any.whl
yarl==1.9.2
yesqa @ file:///Users/***/Library/Caches/pypoetry/artifacts/3d/64/cf/ebad9f41feb1cdc1f3047f3df1443e0713d1a3aae1b9b84fe2fb42099a/yesqa-1.4.0-py2.py3-none-any.whl
zipp==3.16.2
zope.event==5.0
zope.interface==6.0
</details>

### How can we reproduce your problem?
I am using the pymongo and ddtrace in one of work project but the following seems to be the root cuase of the issue:

from ddtrace import patch_all
patch(pymongo=True)

### What is the result that you get?
The above code throws an error below:

**E   AttributeError: type object 'Server' has no attribute 'get_socket'**

<details>
/usr/local/lib/python3.10/site-packages/_pytest/runner.py:341: in from_call
    result: Optional[TResult] = func()
/usr/local/lib/python3.10/site-packages/_pytest/runner.py:372: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
/usr/local/lib/python3.10/site-packages/_pytest/python.py:531: in collect
    self._inject_setup_module_fixture()
/usr/local/lib/python3.10/site-packages/_pytest/python.py:545: in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
/usr/local/lib/python3.10/site-packages/_pytest/python.py:310: in obj
    self._obj = obj = self._getobj()
/usr/local/lib/python3.10/site-packages/_pytest/python.py:528: in _getobj
    return self._importtestmodule()
/usr/local/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/usr/local/lib/python3.10/site-packages/_pytest/pathlib.py:565: in import_path
    importlib.import_module(module_name)
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/usr/local/lib/python3.10/site-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
cron/tests/unit_tests/test_model_cache_updater.py:3: in <module>
    from cron import model_cache_updater
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/usr/local/lib/python3.10/site-packages/ddtrace/internal/module.py:220: in _exec_module
    self.loader.exec_module(module)
<my module's name (omitted to hide info)>: in <module>
    patch_all(logging=True)
/usr/local/lib/python3.10/site-packages/ddtrace/_monkey.py:203: in patch_all
    patch(raise_errors=False, **modules)
/usr/local/lib/python3.10/site-packages/ddtrace/_monkey.py:231: in patch
    when_imported(module)(
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py:284: in register
    register_post_import_hook(hook, name)
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/decorators.py:470: in _synchronized
    return wrapped(*args, **kwargs)
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/importer.py:82: in register_post_import_hook
    hook(module)
/usr/local/lib/python3.10/site-packages/ddtrace/_monkey.py:166: in on_import
    imported_module.patch()
/usr/local/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py:[33](https://gitlab.com/rivian/vt/data-platform/data-cesium/-/jobs/5356344284#L33): in patch
    patch_pymongo_module()
/usr/local/lib/python3.10/site-packages/ddtrace/contrib/pymongo/patch.py:[53](https://gitlab.com/rivian/vt/data-platform/data-cesium/-/jobs/5356344284#L53): in patch_pymongo_module
    _w("pymongo.server", "Server.get_socket", traced_get_socket)
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py:882: in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py:822: in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py:812: in resolve_path
    original = lookup_attribute(parent, attribute)
/usr/local/lib/python3.10/site-packages/ddtrace/vendor/wrapt/wrappers.py:[80](https://gitlab.com/rivian/vt/data-platform/data-cesium/-/jobs/5356344284#L80)4: in lookup_attribute
    return getattr(parent, attribute)
E   AttributeError: type object 'Server' has no attribute 'get_socket'
</details>

### What is the result that you expected?
no error

**Comment by brettlangdon** [comment]
hey @mapuri thanks for reaching out. We've had this reported and fixed in https://github.com/DataDog/dd-trace-py/pull/6736.

This fix was released in 1.18.3 (it should also be available in 2.1.1). Your `pip freeze` is showing `1.18.0`, can you double check that you are indeed using `ddtrace>=1.18.3`?

**Comment by mapuri** [comment]
@brettlangdon thanks for a quick reply. I can confirm that updating ddtrace to 1.18.3 fixes the issue. 

I do remember updating ddtrace to 2.1.1 and still seeing the issue. However, I likely overlooked some details following those steps. Thanks again for your quick support here!
